# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/diman/src/dianm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/diman/src/dianm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diman/src/dianm/CMakeFiles /home/diman/src/dianm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diman/src/dianm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dainm

# Build rule for target.
dainm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dainm
.PHONY : dainm

# fast build rule for target.
dainm/fast:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/build
.PHONY : dainm/fast

#=============================================================================
# Target rules for targets named dainm_tests

# Build rule for target.
dainm_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dainm_tests
.PHONY : dainm_tests

# fast build rule for target.
dainm_tests/fast:
	$(MAKE) -f CMakeFiles/dainm_tests.dir/build.make CMakeFiles/dainm_tests.dir/build
.PHONY : dainm_tests/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

src/DataGenerator.o: src/DataGenerator.cpp.o

.PHONY : src/DataGenerator.o

# target to build an object file
src/DataGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/DataGenerator.cpp.o
.PHONY : src/DataGenerator.cpp.o

src/DataGenerator.i: src/DataGenerator.cpp.i

.PHONY : src/DataGenerator.i

# target to preprocess a source file
src/DataGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/DataGenerator.cpp.i
.PHONY : src/DataGenerator.cpp.i

src/DataGenerator.s: src/DataGenerator.cpp.s

.PHONY : src/DataGenerator.s

# target to generate assembly for a file
src/DataGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/DataGenerator.cpp.s
.PHONY : src/DataGenerator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/preprocessing.o: src/preprocessing.cpp.o

.PHONY : src/preprocessing.o

# target to build an object file
src/preprocessing.cpp.o:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/preprocessing.cpp.o
.PHONY : src/preprocessing.cpp.o

src/preprocessing.i: src/preprocessing.cpp.i

.PHONY : src/preprocessing.i

# target to preprocess a source file
src/preprocessing.cpp.i:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/preprocessing.cpp.i
.PHONY : src/preprocessing.cpp.i

src/preprocessing.s: src/preprocessing.cpp.s

.PHONY : src/preprocessing.s

# target to generate assembly for a file
src/preprocessing.cpp.s:
	$(MAKE) -f CMakeFiles/dainm.dir/build.make CMakeFiles/dainm.dir/src/preprocessing.cpp.s
.PHONY : src/preprocessing.cpp.s

tests/tests.o: tests/tests.cpp.o

.PHONY : tests/tests.o

# target to build an object file
tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/dainm_tests.dir/build.make CMakeFiles/dainm_tests.dir/tests/tests.cpp.o
.PHONY : tests/tests.cpp.o

tests/tests.i: tests/tests.cpp.i

.PHONY : tests/tests.i

# target to preprocess a source file
tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/dainm_tests.dir/build.make CMakeFiles/dainm_tests.dir/tests/tests.cpp.i
.PHONY : tests/tests.cpp.i

tests/tests.s: tests/tests.cpp.s

.PHONY : tests/tests.s

# target to generate assembly for a file
tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/dainm_tests.dir/build.make CMakeFiles/dainm_tests.dir/tests/tests.cpp.s
.PHONY : tests/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dainm"
	@echo "... dainm_tests"
	@echo "... Catch2WithMain"
	@echo "... Catch2"
	@echo "... src/DataGenerator.o"
	@echo "... src/DataGenerator.i"
	@echo "... src/DataGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/preprocessing.o"
	@echo "... src/preprocessing.i"
	@echo "... src/preprocessing.s"
	@echo "... tests/tests.o"
	@echo "... tests/tests.i"
	@echo "... tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

